# Generated by Django 4.2.6 on 2023-10-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_campus_floor_room_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campus",
            name="faculty",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="web.faculty"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="room",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="web.room"
            ),
        ),
    ]
