# Generated by Django 4.2.6 on 2023-10-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_application_user_campus_faculty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="address",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campus",
            name="contact_number",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campus",
            name="head",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campus",
            name="price",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
