# Generated by Django 4.2.6 on 2023-10-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_campus_address_campus_contact_number_campus_head_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="number_application",
            field=models.CharField(max_length=50),
        ),
    ]
